[general]
working_directory = "/Users/danielvallejo/" # Path to the working directory

[cursor]
style = { shape="Beam", blinking="On" }
unfocused_hollow = true
#blinking = "On"
 
[env]
TERM = "xterm-256color"
 
[font]
size = 15.5
 
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
 
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"
 
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
 
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
 
[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"
 
[mouse]
hide_when_typing = true
 
[window]
opacity = 0.8

